### ISSUE TITLE
npm install not working in example folder

### ISSUE THREAD

**Issue by hakkikonu** [sijav/react-native-ip-sec-vpn#1]
package.json in example folder contains 

`"react-native-ip-sec-vpn": "link:../"` line

and when I try to use npm install on example folder, it returns below error.

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../
```

**Comment by sijav** [comment]
Oh my bad link is a yarn invention I have updated the document, thanks...
