### ISSUE TITLE
Is it compatible with Expo SDK 39 + React native 0.63.3?

### ISSUE THREAD

**Issue by mauriciobatistaneves** [sijav/react-native-ip-sec-vpn#6]
Hello, I tried to use this lib with Expo SDK 39 + React native 0.63.3 and when trying to start the app, the errors appear: 

`TypeError: null is not an object (evaluating 'react_native_1.NativeModules.RNIpSecVpn.prepare')

Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.`

Does anyone know how to tell me it is compatible? I am in urgent need of a VPN client for react native.

**Comment by sijav** [comment]
Sorry for late answer but this plugin is not expo ready, I'll check for it but I don't have free time right now.
However any contribution is welcome

**Comment by mauriciobatistaneves** [comment]
Many thanks for the reply.
